/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proyecto_sencillo;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.Async;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class App {
    
    static final class ShutdownHandler extends Thread
	{
		private final Thread t = Thread.currentThread();

		ShutdownHandler register()
		{
			Runtime.getRuntime().addShutdownHook(this);
			return this;
		}

		void unregister()
		{
			Runtime.getRuntime().removeShutdownHook(this);
		}

		@Override
		public void run()
		{
			t.interrupt();
		}
	}
	@GetMapping("/hello")
	@Async
    public String hello(@RequestParam(value = "name", defaultValue = "World") String name) {
		
		
		return String.format("Hello %s!", name);
    }
	    public static void main(String[] args) {
	   //crear las ips
	   Light l1 = new Light(1,1,40,"Light","192.168.1.51");
	   Light l2 = new Light(1,1,20,"Light 2","192.168.2.1");
	   l1.start();
	   l2.start();

	   LightWithDimmer d1 = new LightWithDimmer("Light with Dimmer",1,1,41,"192.168.3.1",100);
	   d1.start();
	   
	   SpringApplication.run(App.class, args);
    }
}
