/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proyecto_sencillo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import io.calimero.GroupAddress;

@SpringBootApplication
public class App {

	static final class ShutdownHandler extends Thread {
		private final Thread t = Thread.currentThread();

		ShutdownHandler register() {
			Runtime.getRuntime().addShutdownHook(this);
			return this;
		}

		void unregister() {
			Runtime.getRuntime().removeShutdownHook(this);
		}

		@Override
		public void run() {
			t.interrupt();
		}
	}

	public static void main(String[] args) {
		// crear las ips

		//LightWithDimmer d1 = new LightWithDimmer("d1","Light with Dimmer", 1, 1, 51, "192.168.1.51", 100);
		//d1.start();

		//LightWithDimmer d2 = new LightWithDimmer("d2","LwD - VMWare", 1, 1, 131, "192.168.1.131", 50);
		//d2.start();

		SpringApplication.run(App.class, args);
	}
}
